### ISSUE TITLE
Add legacy Brave derivation path

### ISSUE THREAD

**Issue by kumavis** [MetaMask/key-tree#1]
https://github.com/brave/eth-hd-keyring/blob/482acf341f01a8d1e924d55bfdbd309444a78e46/test/index.js#L10-L12

> we use different code paths for 12 vs 24. 12-word does the same thing as metamask (needed for legacy compatibility with metamask imports) whereas 24 uses our own derivation method, described here: https://github.com/brave/brave-browser/wiki/Brave-Ethereum-Remote-Client-Wallet-Seed-Information

HKDF-SHA256

**Comment by Mrtenz** [comment]
It mentions this on the page:
> The following only applies to Crypto Wallets Version 1.0.26 or earlier. Later versions use the same key derivation path and passphrase encryption scheme as Metamask.
Do we still want to do this?

**Comment by rekmarks** [comment]
I'm labeling this as `wontfix` and closing for now. If our users ask for it we can revisit.
