### ISSUE TITLE
deriveKeyFromPath should have some input validation

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/key-tree#2]
`deriveKeyFromPath` takes a `fullPath` parameter without validating that the string is formatted correctly. We should do a RegEx pattern check to make sure that the path isn't obviously wrong.

Motivated by string splicing error here: https://github.com/MetaMask/metamask-snaps-beta/blob/f069030/app/scripts/controllers/permissions/restrictedMethods.js/#L159-L175

**Comment by kumavis** [comment]
nice, added
