### ISSUE TITLE
Use `@noble` packages wherever possible

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/key-tree#36]
We should migrate our secp256k1 cryptography to [`@noble/secp256k1`](https://www.npmjs.com/package/@noble/secp256k1).

**Comment by Mrtenz** [comment]
Do we want to replace the use of Node.js `crypto` libraries with their Noble-equivalents too? E.g. replacing `createHmac('sha521')` with [`@noble/hashes/hmac`](https://github.com/paulmillr/noble-hashes#hmac)?

**Comment by FrederikBolding** [comment]
If we use noble we at least know that we are using the same implementation in both places? It seems that `createHmac` (and others) aren't available in the browser.
