### ISSUE TITLE
Generate extended public and private keys

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/key-tree#44]
We should add some functionality to get an extended public (`xpub`) and private key (`xprv`). This will require keeping track of the parent fingerprint, index, and depth.

[`@noble/hashes`](https://github.com/paulmillr/noble-hashes) and [`@scure/base`](https://github.com/paulmillr/scure-base) can be used for most of the required cryptographic functions, like RIPEMD-160 and Base58Check.

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps--Core-615b3a7c08d2b20015eb6c4e/issues/MetaMask/key-tree/44?planning-poker) with ZenHub @FrederikBolding @hmalik88 @Mrtenz @ritave
