### ISSUE TITLE
Public key derivation

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/key-tree#46]
Currently we only support `private parent key → private child key` derivation. Deriving public child keys allows for sharing public keys, without needing to expose private keys.

For reference:
- https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#public-parent-key--public-child-key
- https://github.com/satoshilabs/slips/blob/master/slip-0010.md#public-parent-key--public-child-key

Note that this isn't supported by `ed25519`, as it only works with hardened keys.

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps--Core-615b3a7c08d2b20015eb6c4e/issues/MetaMask/key-tree/46?planning-poker) with ZenHub @FrederikBolding @ritave @hmalik88 @Mrtenz
