### ISSUE TITLE
Invalid hex string when using getBIP44AddressKeyDeriver

### ISSUE THREAD

**Issue by alanorwick** [MetaMask/key-tree#62]
Hello,

I'm attempting to follow the below example in the snaps tutorial and am receiving Invalid hex string "undefined" on the getBIP44AddressKeyDeriver function. I'm assuming this is coming from the chainCode or publicKey coming in as null from the snap_getBig44Entropy_3 request.

Was wondering if anyone has seen this before or has a solution to it.

Thank you!

![Screen Shot 2022-05-17 at 8 23 35 PM](https://user-images.githubusercontent.com/14866363/168938069-34d961b9-7271-4ba7-9e2c-d902e6a65f27.png)
<img width="1060" alt="Screen Shot 2022-05-17 at 8 23 59 PM" src="https://user-images.githubusercontent.com/14866363/168938077-d4b3d6a1-3cfc-4833-b8b8-65a7cc243bce.png">

**Comment by Mrtenz** [comment]
`key-tree` 4 is not used in the extension yet, and the output of `key-tree` 3 (returned by `snap_getBip44Entropy_3`) isn't compatible with version 4. For now you can use `key-tree@3.0.1` instead until MetaMask/metamask-extension#14700 is merged and released.
