### ISSUE TITLE
deriveBIP44AddressKey throw Error: Invalid hex string: "undefined".

### ISSUE THREAD

**Issue by Jeremyyang** [MetaMask/key-tree#64]
Hi, I try to request a `JsonBIP44CoinTypeNode`, then use `deriveBIP44AddressKey` to derive an address, `deriveBIP44AddressKey` returns me an error. Code is as follows:

```js
import {
  deriveBIP44AddressKey,
  JsonBIP44CoinTypeNode,
} from "@metamask/key-tree";

const bip44Node = await wallet.request({
    method: `snap_getBip44Entropy_501`,
    params: [],
}) as JsonBIP44CoinTypeNode;

const extendedPrivateKey = await deriveBIP44AddressKey(bip44Node, {
    account: 0,
    address_index: 0
}).catch((err: Error) => {
    console.error(err); // Error: Invalid hex string: "undefined". 
    // todo
})
```

I reviewed the source code of `@metamask/key-tree`. The error is thrown by `getNode` method because `bip44Node.publicKey` is `undefined`.

Maybe `wallet.request` returns the wrong result, or maybe there is a bug in `@metamask/key-tree`?

Latest Metamask Flask chrome extension, and "@metamask/key-tree": "^4.0.0"`

**Comment by FrederikBolding** [comment]
Hey there! Thanks for reporting.

The current version of Flask `10.15.x` does not have the latest version of `@metamask/key-tree` and is incompatible with `4.0.0`. From Flask `10.16.0` and onwards only `@metamask/key-tree` `4.0.0` and up will be compatible.

So you'll have to use version 3 of `key-tree` for a week or two more before the new version of Flask comes out!

**Comment by rekmarks** [comment]
Since there are solutions / workarounds and this problem is about to go away, I will now close this issue.
