### ISSUE TITLE
getBIP44AddressKeyDeriver throw Error: Invalid hex string: "undefined"

### ISSUE THREAD

**Issue by Jeremyyang** [MetaMask/key-tree#67]
Hi, I try to request a JsonBIP44CoinTypeNode, then use getBIP44AddressKeyDeriver to derive an address, just like the reference in [the guide](https://docs.metamask.io/guide/snaps-rpc-api.html#unrestricted-methods).

```js
import {
  getBIP44AddressKeyDeriver,
  JsonBIP44CoinTypeNode,
} from "@metamask/key-tree";

const bip44Node = await wallet.request({
    method: `snap_getBip44Entropy_501`,
    params: [],
}) as JsonBIP44CoinTypeNode;

const deriveSolCoinAddress = await getBIP44AddressKeyDeriver(bip44Node, {
    account: 0,
    change: 0,
}).catch((err: Error) => {
    console.error(err); // Error: Invalid hex string: "undefined". 
    // todo
});
```

The error still seems to exist, just like issue [MetaMask/key-tree/issues/64](https://github.com/MetaMask/key-tree/issues/64).

I have updated to the latest Metamask Flask@10.16.1.0, and "@metamask/key-tree": "^4.0.0"`

**Comment by FrederikBolding** [comment]
`10.16.2` has been released and you should be able to use `4.0.0` now! Please open another issue if you still have problems.
